name: Build extension
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  chrome:
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Build for Chrome
        env:
          EXTENSION_BROWSER_TARGET: chrome
        run: yarn build:extension
      - uses: actions/upload-artifact@v3
        with:
          name: tab-chrome
          path: apps/extension/dist/
  firefox:
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Build for Firefox
        env:
          EXTENSION_BROWSER_TARGET: firefox
        run: yarn build:extension
      - uses: actions/upload-artifact@v3
        with:
          name: tab-firefox
          path: apps/extensions/dist/

